#!/bin/bash
 clear
    read -p "Enter an Position " Position
         bash ./makoscript $Position 
         i=0  
       touch Result
       rm Result
       echo "Now lets run the makoscript 5 times"
       while [ $i -lt 5 ]
       do
       read -p "Enter a Diffrente Position (Position number $(( $i + 1 )) ) " r
         bash ./makoscript $r >> Result
         i=$(( $i + 1 ))
       cat Result
       done
       echo "Result has been added to your directory"
